/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : HTML Converter
 #	author : miyako
 #	2012/08/27
 #
 # --------------------------------------------------------------------------------*/

#include <fstream>

BOOL readPath(CUTF8String *path, CUTF8String *html);
BOOL checkPath(CUTF8String *path);

// --- Convert
void HTML_Convert_to_image(sLONG_PTR *pResult, PackagePtr pParams);
void HTML_Convert_to_pdf(sLONG_PTR *pResult, PackagePtr pParams);

//Image settings (HTML_Convert_to_image)

/*the following settings are const in this plugin
 in
 out
 */

#define HTML_IMAGE_CROP_LEFT			1	//numeric
#define HTML_IMAGE_CROP_TOP				2	//numeric
#define HTML_IMAGE_CROP_WIDTH			3	//numeric
#define HTML_IMAGE_CROP_HEIGHT			4	//numeric
#define HTML_IMAGE_JPEG_QUALITY			5	//numeric
#define HTML_IMAGE_USE_SMART_WIDTH		6	//bool
#define HTML_IMAGE_SCREEN_WIDTH			7	//numeric
#define HTML_IMAGE_FORMAT				8	//jpg|png|bmp|svg
#define HTML_IMAGE_USE_BACKGROUND		9	//bool (inverse)

//Web page specific settings (shared)

#define HTML_USE_BACKGROUND				10	//bool
#define HTML_USE_IMAGES					11	//bool
#define HTML_USE_JAVASCRIPT				12	//bool
#define HTML_USE_SMART_RESIZE			13	//bool
#define HTML_MINIMUM_FONT_SIZE			14	//numeric
#define HTML_USE_PRINT_MEDIA			15	//bool
#define HTML_DEFAULT_ENCODING			16	//string
#define HTML_CUSTOM_CSS_PATH			17	//string (path)
#define HTML_USE_PLUGINS				18	//bool

//Object Specific loading settings (shared) 

/*the following settings are const in this plugin
 load.blockLocalFileAccess
 load.stopSlowScript
 load.debugJavascript
 load.loadErrorHandling
 */

#define HTML_ZOOM_FACTOR				19	//numeric
#define HTML_COOKIE_JAR_PATH			20	//string (path)

//Pdf global settings (HTML_Convert_to_pdf)

/*the following settings are const in this plugin
 includeInOutline
 out
 */

#define HTML_PDF_PAPER_SIZE				21	//string
#define HTML_PDF_DOCUMENT_WIDTH			22	//string
#define HTML_PDF_DOCUMENT_HEIGHT		23	//string
#define HTML_PDF_ORIENTATION			24	//string (constant)
#define HTML_PDF_COLOR_MODE				25	//string (constant)
#define HTML_PDF_DPI					26	//numeric
#define HTML_PDF_JPEG_QUALITY			27	//numeric
#define HTML_PDF_IMAGE_DPI				28	//numeric
#define HTML_PDF_OUTPUT_FORMAT			29	//string (constant)
#define HTML_PDF_MARGIN_RIGHT			30	//string
#define HTML_PDF_MARGIN_LEFT			31	//string
#define HTML_PDF_MARGIN_BOTTOM			32	//string
#define HTML_PDF_MARGIN_TOP				33	//string
#define HTML_PDF_USE_COMPRESSION		34	//bool
#define HTML_PDF_DOCUMENT_TITLE			35	//string
#define HTML_PDF_PAGE_NUMBER_OFFSET		36	//numeric
#define HTML_PDF_NUMBER_OF_COPIES		37	//numeric
#define HTML_PDF_USE_COLLATE			38	//bool
#define HTML_PDF_USE_OUTLINE			39	//bool
#define HTML_PDF_OUTLINE_DEPTH			40	//numeric
#define HTML_PDF_HEADER_FONT_SIZE		41	//numeric
#define HTML_PDF_HEADER_FONT_NAME		42	//string
#define HTML_PDF_HEADER_LEFT			43	//string
#define HTML_PDF_HEADER_CENTER			44	//string
#define HTML_PDF_HEADER_RIGHT			45	//string
#define HTML_PDF_HEADER_USE_LINE		46	//bool
#define HTML_PDF_HEADER_SPACE			47	//numeric
#define HTML_PDF_FOOTER_FONT_SIZE		48	//numeric
#define HTML_PDF_FOOTER_FONT_NAME		49	//string
#define HTML_PDF_FOOTER_LEFT			50	//string
#define HTML_PDF_FOOTER_CENTER			51	//string
#define HTML_PDF_FOOTER_RIGHT			52	//string
#define HTML_PDF_FOOTER_USE_LINE		53	//bool
#define HTML_PDF_FOOTER_SPACE			54	//numeric
#define HTML_PDF_TOC_USE_DOTTED_LINES	55	//bool
#define HTML_PDF_TOC_CAPTION_TEXT		56	//string
#define HTML_PDF_TOC_USE_FORWARD_LINKS	57	//bool
#define HTML_PDF_TOC_USE_BACK_LINKS		58	//bool
#define HTML_PDF_TOC_INDENTATION		59	//numeric
#define HTML_PDF_TOC_FONT_SCALE			60	//numeric
#define HTML_PDF_USE_EXTERNAL_LINKS		61	//bool
#define HTML_PDF_USE_LOCAL_LINKS		62	//bool
#define HTML_PDF_USE_FORMS				63	//bool
#define HTML_PDF_USE_PAGES_COUNT		64	//bool
#define HTML_PDF_OUTLINE_PATH			65	//string (path)
#define HTML_PDF_OUTLINE_XSL_PATH		66	//string (path)

//Object Specific loading settings (shared, internet)

#define HTML_WEB_USERNAME				67
#define HTML_WEB_PASSWORD				68
#define HTML_WEB_PROXY					69
